### ISSUE TITLE
Gasket 1006351A, spaces for indicators not centered

### ISSUE THREAD

**Issue by lathoub** [rrainey/agc-mechanical-cad#10]
Hi,
I believe that the holes in [Gasket 1006351A](https://github.com/rrainey/agc-mechanical-cad/blob/master/agc-block-ii/1006350A-exact-GASKET%2C%20RETAINED.f3d) for the indicators are not centered. Unfortunately, I'm bad at editing in Fusion 360, as I would have centered it myself.

Am I seeing it right?
Thanks!

The reference drawing indicates a distance of 0.080 inch, but in the drawing the distance vary from 0.082 to 0.02 inch.

![Screenshot 2023-04-16 at 16 42 28](https://user-images.githubusercontent.com/4082369/232320897-fefa5ca4-5896-4658-8632-b4aeeeaa8aa7.png)

![Screenshot 2023-04-16 at 16 42 45](https://user-images.githubusercontent.com/4082369/232320824-22e1c419-08ef-487a-af46-b7f96df5229e.png)

![Screenshot 2023-04-16 at 16 43 31](https://user-images.githubusercontent.com/4082369/232320826-488a9393-a5ab-44f4-8a03-78d6699e60b0.png)

![Screenshot 2023-04-16 at 16 43 49](https://user-images.githubusercontent.com/4082369/232320829-0b0c231a-0c08-444e-b154-651f744340d3.png)

![Screenshot 2023-04-16 at 16 44 27](https://user-images.githubusercontent.com/4082369/232320831-e8252ea1-85be-428c-a439-ecda4982704a.png)

(When I overlay the printed 1006351A over [2004968E](https://github.com/rrainey/agc-mechanical-cad/blob/master/agc-block-ii/2004968E-exact-HOUSING%2C%20FRONT.f3d), the holes for the indicators are also not centered).

**Comment by rrainey** [comment]
I'll have a look at it this week.

**Comment by rrainey** [comment]
I pushed a fix for the issue on the left side cutout.  Have a look.

**Comment by lathoub** [comment]
Perfect - thanks @rrainey
