### ISSUE TITLE
No Issue

### ISSUE THREAD

**Issue by bschymanski** [rrainey/agc-mechanical-cad#2]
Hi, 

i have no issue at all and want to thank you for making these files available!

Fantastic work. I enjoy working with them in Fusion360 to prepare them for 3d printing and adjusting little things so i can assemble them with M3 Screws for example.

All the best

Bernd

**Comment by rrainey** [comment]
I'm glad to read you are enjoying this work.  I am creating a project derived from this repo specifically for 3D printing.  It would include versions of these models with appropriate insert holes and other Additive Manufacturing optimizations like I think you are describing.  It would allow for using Ben Krasnow's EL display along with my Alarm Panel and modular keyboard replica projects. 

If you are interested in collaborating, let me know.

**Comment by bschymanski** [comment]
I printed the parts for one of the buttons and they work great mechanically! But i have to design a screw (?)  to fix it to the Housing.

Also printed the "2004918B-exact-HOUSING, FRONT" in one piece. It worked, but i didn't like the fact that i had to use supports.
I split the model in half and right now i am printing the second half to see if they fit together afterwards.
On the left side is not enough "flesh" for 3D printig and there are two gaps (i attached you a photo to make clear what i mean)
I tried to fix it, but there are dependencys that i have to understand better.

But i am by no means a gifted Fusion360 user nor a programmer of any sorts, but i own one of the OpenDSKY Kits. It works and is close to the original, but not exactly. 
Don't like the buttons of the though.

But the people in the OpenDSKY Google Group are nice and they started to build a more realistic model. And they are in the process of creating an alternativ EL Display, but haven't released the PCB files yet.

The EL-Display is the biggest problem i guess. Ben Krasnow's EL display would be great to have, but i would not know how to build it on my own. The process is quite demanding.

Might i mention your work in the OpenDSKY Group? (https://groups.google.com/forum/#!forum/opendsky)

Bernd

(Sorry for my english, i am not a native speaker)

![IMG_20200729_212439](https://user-images.githubusercontent.com/34037236/88843985-43e33800-d1e2-11ea-9346-757c398cc786.jpg)
![housing right side](https://user-images.githubusercontent.com/34037236/88844035-55c4db00-d1e2-11ea-9eea-bc5ec3464667.png)

**Comment by bschymanski** [comment]
Hi again,
i figured it out with the side, had to use the extrude function instead of the press-pull function.
Now it slices well for both sides. I should have checked the sliced model before printing....

**Comment by rrainey** [comment]
Yes. I have seen that issue, although it "prints" without a physical gap on the SLS print process that I use. 

It's on my list to examine and repair -- For what it is worth, I have been trying to maintain fidelity with the original drawings in all cad models.  There is probably some measurement in that overall model that's simply not to spec with the original drawing.  If it's OK with you, I will create a separate issue to track resolution of this problem.

There is also a more minor issue with the Front Cover part that I need to address. It is easy to fix after printing, so it is maybe less urgent.  I'll open an issue on that tonight as well.

Feel free to share your experiences here with other project teams. I'm happy to collaborate where I have time. On the EL Display side, I have been building several copies of Ben Krasnow's display. I'm planning to complete the final stack-up this week. Maybe I can post some videos if it works for me as well as it did for him.

**Comment by rrainey** [comment]
I committed what I hope is a fix. Have a look.
