### ISSUE TITLE
2004918B Front Housing - right side wells too close to edge

### ISSUE THREAD

**Issue by rrainey** [rrainey/agc-mechanical-cad#4]
<img width="739" alt="2004918B-bug" src="https://user-images.githubusercontent.com/271126/88863638-eabada80-d1c8-11ea-9608-95f455954456.PNG">
The two wells (circled) are place too close to the right edge of the piece. This leave the rightmost wall too thin for most 3D printing processes.

**Comment by rrainey** [comment]
I have committed a candidate fix.

**Comment by bschymanski** [comment]
That looks much better, i am pretty shure it will print OK
